n = input('Qual o nome do aluno?')
f = input('Quantas faltas o/a {} tem?'.format(n))
t = input('Qual o número da turma do(a) {}?'.format(n))
n1 = input('Qual o nome do aluno?')
f1 = input('Quantas faltas o/a {} tem?'.format(n1))
t1 = input('Qual o número da turma do(a) {}?'.format(n1))
n2 = input('Qual o nome do aluno?')
f2 = input('Quantas faltas o/a {} tem?'.format(n2))
t2 = input('Qual o número da turma do(a) {}?'.format(n2))
print('---------------Tabela---------------')
print('{} da turma {}: Tem {} faltas.'.format(n, t, f))
print('------------------------------------')
print('{} da turma {}: Tem {} faltas.'.format(n1, t1, f1))
print('------------------------------------')
print('{} da turma {}: Tem {} faltas.'.format(n2, t2, f2))
print('------------------------------------')
